export const menulist:menuItem[] = [
    {
        title:'聊天',
        desc:'这是聊天',
        btn:'去聊天',
        url:'/chat'
    },
    {
        title:'webgl',
        desc:'我的webgl',
        btn:'去webgl',
        url:'/webgl'
    },
    {
        title:'agent',
        desc:'我的agent',
        btn:'去agent',
        url:'/agent'
    },
]